### ISSUE TITLE
Correction in CO_Histogram_AMI_even_2_5 implementation

### ISSUE THREAD

**Issue by imraniac** [chlubba/catch22#11]
Referring to this code snippet in CO_AutoCorr.c 
```
#define tau 2
#define numBins 5

double CO_HistogramAMI_even_2_5(const double y[], const int size)
```
Why **tau** is 2 and **numBins** is 5? Shouldn't it be vice-versa according to the implementation of _hctsa_ feature

**Comment by chlubba** [comment]
Hi @imraniac,

why do you think so? If you take a look into the Master Operation definitions in 
https://github.com/benfulcher/hctsa/blob/master/Database/INP_mops.txt
you see that `CO_HistogramAMI_even_5` is computed using 5 bins (for taus between 1 and 5). 

The `CO_Histogram_AMI` function is defined here
https://github.com/benfulcher/hctsa/blob/master/Operations/CO_HistogramAMI.m

Two bins would be quite few anyway.

**Comment by imraniac** [comment]
I thought you were using `CO_HistogramAMI_even_2` feature. Actually I m trying to implement `CO_HistogramAMI_even_2_3`, I got confused by the name of the function in code, my bad.

Thanks for the clarification.

**Comment by chlubba** [comment]
No worries! Good luck with your implementation
