### ISSUE TITLE
Error installing R wrapper (+ fixes for docs)

### ISSUE THREAD

**Issue by danlurie** [chlubba/catch22#3]
Been trying to install the R wrapper without much success (though more success than I've had with the Python and Matlab wrappers!). I noticed a few issues with the documentation along the way, and have noted them here along with the error I get:

The install docs refer to`./C_functions`, but this directory appears to be`./C` in current builds.

I think the .c and .h files are supposed to be moved to `./wrap_R/catch22/src`, rather than  `./wrap_R/src` (which is specified in the install instructions, but does not actually exist unless I manually create it). 

Running `R CMD INSTALL catch22_x.y.tar.gz` only “works” in the latter case, and then only if `R CMD build catch22` was run *after* the .c and .h files are copied to `./wrap_R/catch22/src`. Attempting to build with these files in `./wrap_R/src`  causes the following error:

```
catch22_wrap.cpp:5:25: fatal error: CO_AutoCorr.h: No such file or directory
```

The docs should clarify that users should replace `catch22_x.y.tar.gz` with the tar file generated by the previous step. The name of this fill will depend on their version of catch22.

Fixing the error related to the location of the C files got me as far as the following error. Any advice would be appreciated: 

```
(r-environment) # dlurie@nx2 in ~/Software/catch22/wrap_R [17:55:06]
$ R CMD INSTALL catch22_0.1.tar.gz
* installing to library \u2018/home/despoB/dlurie/anaconda3/envs/r-environment/lib/R/library\u2019
* installing *source* package \u2018catch22\u2019 ...
** libs
gcc -std=gnu99 -I/home/despoB/dlurie/anaconda3/envs/r-environment/lib/R/include -DNDEBUG -I../inst/include -I"/home/despoB/dlurie/anaconda3/envs/r-environment/lib/R/library/Rcpp/include" -I/home/despoB/dlurie/anaconda3/envs/r-environment/include   -fpic  -I/home/despoB/dlurie/anaconda3/envs/r-environment/include  -c CO_AutoCorr.c -o CO_AutoCorr.o
In file included from CO_AutoCorr.c:8:0:
CO_AutoCorr.c: In function \u2018CO_AutoCorr\u2019:
fft.h:16:43: error: \u2018_Imaginary_I\u2019 undeclared (first use in this function)
 #define CMPLX(x, y) ((cplx)((double)(x) + _Imaginary_I * (double)(y)))
                                           ^
CO_AutoCorr.c:63:16: note: in expansion of macro \u2018CMPLX\u2019
         F[i] = CMPLX(y[i] - m, 0.0);
                ^
fft.h:16:43: note: each undeclared identifier is reported only once for each function it appears in
 #define CMPLX(x, y) ((cplx)((double)(x) + _Imaginary_I * (double)(y)))
                                           ^
CO_AutoCorr.c:63:16: note: in expansion of macro \u2018CMPLX\u2019
         F[i] = CMPLX(y[i] - m, 0.0);
                ^
CO_AutoCorr.c: In function \u2018co_autocorrs\u2019:
fft.h:16:43: error: \u2018_Imaginary_I\u2019 undeclared (first use in this function)
 #define CMPLX(x, y) ((cplx)((double)(x) + _Imaginary_I * (double)(y)))
                                           ^
CO_AutoCorr.c:97:16: note: in expansion of macro \u2018CMPLX\u2019
         F[i] = CMPLX(y[i] - m, 0.0);
                ^
make: *** [CO_AutoCorr.o] Error 1
ERROR: compilation failed for package \u2018catch22\u2019
* removing \u2018/home/despoB/dlurie/anaconda3/envs/r-environment/lib/R/library/catch22\u2019
```

**Comment by chlubba** [comment]
Hi Dan,

thank you for the detailed error description and suggestions on the readme. Sorry you had to go through all the trouble without success! You are right about the issues and I updated the readme according to your suggestions. 

For the compile error, could you make sure you have Clang installed and retry? I exchanged the `_Imaginary_I` macro with `_Complex_I` to conform with the C11 standard. Hope it works now!

Was it the same error for the other wrappers in Matlab and Python? Thank you!

Best,
Carl
